import os
import json
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

# Use absolute path for the results file relative to this file's directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Modular imports for the data pipeline
from scraping.trustpilot import scrape
from preprocessing import cleaning
from statistics import churn_rate

app = FastAPI(title="SumUp Churn Monitor API")

# Mount static files for frontend
app.mount("/", StaticFiles(directory=os.path.join(BASE_DIR, "..", "frontend"), html=True), name="frontend")

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

ADDED_CHURN_CSV = os.path.join(BASE_DIR, "statistics", "reviews_churn_added.csv")

@app.get("/api/churn/run")
async def run_full_pipeline():
    """Trigger the full pipeline using modular imports: Scrape -> Preprocessing -> Churn Analysis."""
    try:
        # Step 1: SCRAPE - Modular async call
        print("Starting Scrape Phase...")
        await scrape.run()

        # Step 2: PREPROCESSING - Modular call
        print("Starting Normalization Phase...")
        cleaning.run()

        # Step 3: CHURN ANALYSIS - Modular call
        print("Starting Analysis Phase...")
        churn_rate.run()

        return {
            "status": "success",
            "message": "Full pipeline completed via internal modules. Scrape, preprocessing, and analysis refreshed.",
        }
    except Exception as e:
        print(f"Pipeline Error: {e}")
        raise HTTPException(status_code=500, detail=f"Pipeline synchronization failed: {str(e)}")

@app.get("/api/churn/results")
async def get_churn_results():
    """Retrieve the results generated by the churn analysis from a single source of truth."""
    if not os.path.exists(ADDED_CHURN_CSV):
        raise HTTPException(status_code=404, detail="Churn result file not found. Run analysis first.")
    
    try:
        # Read the comprehensive dataset
        df = pd.read_csv(ADDED_CHURN_CSV).fillna("")
        
        # In-memory filtering for specialized outreach lists
        general_outreach_df = df[df['churn_score'] >= 60]
        urgent_business_df = df[(df['churn_score'] >= 60) & (df['is_business'] == True)]
        
        # Calculate overall ecosystem statistics
        avg_rating = float(df['rating'].mean()) if not df.empty else 0.0
        
        # Get file modification time for synchronization metadata
        last_updated = os.path.getmtime(ADDED_CHURN_CSV)
        
        return {
            "general_outreach": general_outreach_df.to_dict(orient="records"),
            "urgent_business": urgent_business_df.to_dict(orient="records"),
            "all_analyzed": df.to_dict(orient="records"),
            "stats": {
                "total_churners": len(general_outreach_df),
                "high_value_businesses": len(urgent_business_df),
                "total_analyzed": len(df),
                "average_rating": round(avg_rating, 1),
                "last_updated": last_updated
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading results: {e}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
